### ISSUE TITLE
sum.js

### ISSUE THREAD

**Issue by azole** [tyzx5246/hello-node#1]
i 這裡要加上 let 宣告，不然 i 就會變成全域變數。

https://github.com/tyzx5246/hello-node/blob/ce5f5ed3395d4c4728d92ad69a1735a1afcb6646/practice/sum.js#L5

**Comment by tyzx5246** [comment]
已補上 let 宣告，謝謝老師提醒。

**Comment by tyzx5246** [comment]
> 我這裡變了要加上通知，我就變全域數字了。
> 
> https://github.com/tyzx5246/hello-node/blob/ce5f5ed3395d4c4728d92ad69a1735a1afcb6646/practice/sum.js#L5



> i 這裡要加上 let 宣告，不然 i 就會變成全域變數。
> 
> https://github.com/tyzx5246/hello-node/blob/ce5f5ed3395d4c4728d92ad69a1735a1afcb6646/practice/sum.js#L5

已補上 let 宣告，謝謝老師提醒。

**Comment by tyzx5246** [comment]
> i 這裡要加上 let 宣告，不然 i 就會變成全域變數。
> 
> https://github.com/tyzx5246/hello-node/blob/ce5f5ed3395d4c4728d92ad69a1735a1afcb6646/practice/sum.js#L5

已補上 let 宣告，謝謝老師提醒。

**Comment by azole** [comment]
很棒，那 issue 就可以關掉了！
